<?php

require_once '../load.php';
confirm_logged_in();

// using the time() and md5() to generated by the system
function get_password( $length = 8 ) {
	$password = substr(md5(time()), 0, $length);
	return $password;
}


if(isset($_POST['submit'])) {
    $username = trim($_POST['username']);
    $password = trim($_POST['password']);
    $email    = trim($_POST['email']);

    if(empty($username) || empty($password) || empty($email)){
        $message = 'Please fill the required field';
    }else{
        $message = createUser($username,$password,$email);
    }
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/main.css">
    <title>User Management - Create User</title>
</head>
<body>
    <h2>Create User</h2>
    <?php echo !empty($message)?$message:''; ?>
    <form action="admin_creatuser.php" method="post">
        <label>UserName</label>
        <input type="text" name="username" value=""><br><br>
        <label>Password (The password is generated by the system) </label>
        <!-- input the password by the system and can not change -->
        <input type="text" name="password" value="<?php echo get_password(8);?>" readonly><br><br>
        <label>Email</label>
        <input type="email" name="email" value=""><br><br>
        <button name="submit">Create User</button>

    </form>
    <?php include '../templates/footer.php';?>

</body>
</html>